### ISSUE TITLE
Error with Axios.get call

### ISSUE THREAD

**Issue by dan-christensen** [acouvreur/ssh-log-to-influx#102]
The Axios.get API call throws an error.

**Comment by dan-christensen** [comment]
`(node:32586) UnhandledPromiseRejectionWarning: Error: Unsuccessful request (undefined): undefined
    at retrieveLocationFromAPI (/ssh-log-to-influx/dist/api.js:59:11)
    at doApiCall (/home/dan/ssh-log-to-influx/dist/api.js:88:22)
    at Socket.socket.on (/ssh-log-to-influx/dist/index.js:54:47)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
(node:32586) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:32586) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
{ Error: Request failed with status code 404
    at createError (/ssh-log-to-influx/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/ssh-log-to-influx/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/ssh-log-to-influx/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
`

**Comment by acouvreur** [comment]
Indeed doApiCall is not inside a try catch. I'll update that

**Comment by acouvreur** [comment]
But the reason why it failed may not be caused by the program. Maybe you have reached the API limit?
Maybe the API I call is not available where you live? Can you provide more infos

**Comment by dan-christensen** [comment]
Yeah for sure, what do you need? I live in the US.

**Comment by acouvreur** [comment]
Your NodeJS version, have you tried running it with Docker? Do you have an influxdb database connected?
Does this http://ip-api.com/json/ returns something to you?

**Comment by dan-christensen** [comment]
I have it running on docker and that's where the error first happened, so I tried building and running it from source and I got the same error. My node version is 10.22.0, yes I have an influxdb, and yes the api returns a json object.
